In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# 환경셋팅
import pandas as pd
import numpy as np

C:\Users\LG\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\LG\anaconda3\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\LG\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [ ]:
# 데이터프레임 선언
dataset = np.array([['kor', 70], ['math', 80]])
df = pd.DataFrame(dataset, columns = ['class', 'score'])
df

  class score
0   kor    70
1  math    80

In [ ]:
# 데이터프레임 출력
from sklearn.datasets import load_iris
iris = load_iris()
iris = pd.DataFrame(iris.data, columns = iris.feature_names)
# 모든 행 출력
pd.set_option('display.max_rows', None)
iris

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
9                  4.9               3.1                1.5               0.1
10                 5.4               3.7                1.5               0.2
11                 4.8               3.4                1.6               0.2
12                 4.8               3.0                1.4               0.1
13                 4.3               3.0                1.1               0.1
14                 5.8               4.0                1.2               0.2
15                 5.7               4.4                1.5               0.4
16                 5.4               3.9                1.3               0.4
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
22                 4.6               3.6                1.0               0.2
23                 5.1               3.3                1.7               0.5
24                 4.8               3.4                1.9               0.2
25                 5.0               3.0                1.6               0.2
26                 5.0               3.4                1.6               0.4
27                 5.2               3.5                1.5               0.2
28                 5.2               3.4                1.4               0.2
29                 4.7               3.2                1.6               0.2
30                 4.8               3.1                1.6               0.2
31                 5.4               3.4                1.5               0.4
32                 5.2               4.1                1.5               0.1
33                 5.5               4.2                1.4               0.2
34                 4.9               3.1                1.5               0.2
35                 5.0               3.2                1.2               0.2
36                 5.5               3.5                1.3               0.2
37                 4.9               3.6                1.4               0.1
38                 4.4               3.0                1.3               0.2
39                 5.1               3.4                1.5               0.2
40                 5.0               3.5                1.3               0.3
41                 4.5               2.3                1.3               0.3
42                 4.4               3.2                1.3               0.2
43                 5.0               3.5                1.6               0.6
44                 5.1               3.8                1.9               0.4
45                 4.8               3.0                1.4               0.3
46                 5.1               3.8                1.6               0.2
47                 4.6               3.2                1.4               0.2
48                 5.3               3.7                1.5               0.2
49                 5.0               3.3                1.4               0.2
50                 7.0               3.2                4.7               1.4
51                 6.4               3.2                4.5               1.5
52                 6.9               3.1                4.9               1.5
53                 5.5               2.3                4.0               1.3
54                 6.5               2.8                4.6               1.5
55                 5.7               2.8                4.5               1.3
56                 6.3               3.3                4.7               1.6
57                 4.9               2.4                3.3               1.0
58                 6.6               2.9                4.6               1.3
59                 5.2               2.7                3.9               1.4
60                 5.0               2.0                3.5               1.0
61                 5.9               3.0                4.2               1.5
62                 6.0               2.2                4.0               1.0
63                 6.1               2.9                4.7               1.4
64                 5.6               2.9                3.6               1.3
65                 6.7               3.1                4.4               1.4
66                 5.6               3.0                4.5               1.5
67                 5.8               2.7                4.1               1.0
68                 6.2               2.2                4.5               1.5
69                 5.6               2.5                3.9               1.1
70                 5.9               3.2                4.8               1.8
71                 6.1               2.8                4.0               1.3
72                 6.3               2.5                4.9               1.5
73                 6.1               2.8                4.7               1.2
74                 6.4               2.9                4.3               1.3
75                 6.6               3.0                4.4               1.4
76                 6.8               2.8                4.8               1.4
77                 6.7               3.0                5.0               1.7
78                 6.0               2.9                4.5               1.5
79                 5.7               2.6                3.5               1.0
80                 5.5               2.4                3.8               1.1
81                 5.5               2.4                3.7               1.0
82                 5.8               2.7                3.9               1.2
83                 6.0               2.7                5.1               1.6
84                 5.4               3.0                4.5               1.5
85                 6.0               3.4                4.5               1.6
86                 6.7               3.1                4.7               1.5
87                 6.3               2.3                4.4               1.3
88                 5.6               3.0                4.1               1.3
89                 5.5               2.5                4.0               1.3
90                 5.5               2.6                4.4               1.2
91                 6.1               3.0                4.6               1.4
92                 5.8               2.6                4.0               1.2
93                 5.0               2.3                3.3               1.0
94                 5.6               2.7                4.2               1.3
95                 5.7               3.0                4.2               1.2
96                 5.7               2.9                4.2               1.3
97                 6.2               2.9                4.3               1.3
98                 5.1               2.5                3.0               1.1
99                 5.7               2.8                4.1               1.3
100                6.3               3.3                6.0               2.5
101                5.8               2.7                5.1               1.9
102                7.1               3.0                5.9               2.1
103                6.3               2.9                5.6               1.8
104                6.5               3.0                5.8               2.2
105                7.6               3.0                6.6               2.1
106                4.9               2.5                4.5               1.7
107                7.3               2.9                6.3               1.8
108                6.7               2.5                5.8               1.8
109                7.2               3.6                6.1               2.5
110                6.5               3.2                5.1               2.0
111                6.4               2.7                5.3               1.9
112                6.8               3.0                5.5               2.1
113                5.7               2.5                5.0               2.0
114                5.8               2.8                5.1               2.4
115                6.4               3.2                5.3               2.3
116                6.5               3.0                5.5               1.8
117                7.7               3.8                6.7               2.2
118                7.7               2.6                6.9               2.3
119                6.0               2.2                5.0               1.5
120                6.9               3.2                5.7               2.3
121                5.6               2.8                4.9               2.0
122                7.7               2.8                6.7               2.0
123                6.3               2.7                4.9               1.8
124                6.7               3.3                5.7               2.1
125                7.2               3.2                6.0               1.8
126                6.2               2.8                4.8               1.8
127                6.1               3.0                4.9               1.8
128                6.4               2.8                5.6               2.1
129                7.2               3.0                5.8               1.6
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0
132                6.4               2.8                5.6               2.2
133                6.3               2.8                5.1               1.5
134                6.1               2.6                5.6               1.4
135                7.7               3.0                6.1               2.3
136                6.3               3.4                5.6               2.4
137                6.4               3.1                5.5               1.8
138                6.0               3.0                4.8               1.8
139                6.9               3.1                5.4               2.1
140                6.7               3.1                5.6               2.4
141                6.9               3.1                5.1               2.3
142                5.8               2.7                5.1               1.9
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

In [ ]:
# 데이터프레임 인덱스 확인/추가/리셋
list(df.index)

[0, 1]

In [ ]:
# set_index()
df.set_index('class', drop = True, append = False, inplace = True)
df

      score
class
kor      70
math     80

In [ ]:
# reset_index()
df.reset_index(drop = False, inplace = True)
df

  class score
0   kor    70
1  math    80

In [ ]:
# 데이터 프레임 컬럼명 확인 및 변경
iris.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [ ]:
iris.columns = ['sepal length', 'sepal width', 'petal length', 'petal width']
iris

     sepal length  sepal width  petal length  petal width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
5             5.4          3.9           1.7          0.4
6             4.6          3.4           1.4          0.3
7             5.0          3.4           1.5          0.2
8             4.4          2.9           1.4          0.2
9             4.9          3.1           1.5          0.1
10            5.4          3.7           1.5          0.2
11            4.8          3.4           1.6          0.2
12            4.8          3.0           1.4          0.1
13            4.3          3.0           1.1          0.1
14            5.8          4.0           1.2          0.2
15            5.7          4.4           1.5          0.4
16            5.4          3.9           1.3          0.4
17            5.1          3.5           1.4          0.3
18            5.7          3.8           1.7          0.3
19            5.1          3.8           1.5          0.3
20            5.4          3.4           1.7          0.2
21            5.1          3.7           1.5          0.4
22            4.6          3.6           1.0          0.2
23            5.1          3.3           1.7          0.5
24            4.8          3.4           1.9          0.2
25            5.0          3.0           1.6          0.2
26            5.0          3.4           1.6          0.4
27            5.2          3.5           1.5          0.2
28            5.2          3.4           1.4          0.2
29            4.7          3.2           1.6          0.2
30            4.8          3.1           1.6          0.2
31            5.4          3.4           1.5          0.4
32            5.2          4.1           1.5          0.1
33            5.5          4.2           1.4          0.2
34            4.9          3.1           1.5          0.2
35            5.0          3.2           1.2          0.2
36            5.5          3.5           1.3          0.2
37            4.9          3.6           1.4          0.1
38            4.4          3.0           1.3          0.2
39            5.1          3.4           1.5          0.2
40            5.0          3.5           1.3          0.3
41            4.5          2.3           1.3          0.3
42            4.4          3.2           1.3          0.2
43            5.0          3.5           1.6          0.6
44            5.1          3.8           1.9          0.4
45            4.8          3.0           1.4          0.3
46            5.1          3.8           1.6          0.2
47            4.6          3.2           1.4          0.2
48            5.3          3.7           1.5          0.2
49            5.0          3.3           1.4          0.2
50            7.0          3.2           4.7          1.4
51            6.4          3.2           4.5          1.5
52            6.9          3.1           4.9          1.5
53            5.5          2.3           4.0          1.3
54            6.5          2.8           4.6          1.5
55            5.7          2.8           4.5          1.3
56            6.3          3.3           4.7          1.6
57            4.9          2.4           3.3          1.0
58            6.6          2.9           4.6          1.3
59            5.2          2.7           3.9          1.4
60            5.0          2.0           3.5          1.0
61            5.9          3.0           4.2          1.5
62            6.0          2.2           4.0          1.0
63            6.1          2.9           4.7          1.4
64            5.6          2.9           3.6          1.3
65            6.7          3.1           4.4          1.4
66            5.6          3.0           4.5          1.5
67            5.8          2.7           4.1          1.0
68            6.2          2.2           4.5          1.5
69            5.6          2.5           3.9          1.1
70            5.9          3.2           4.8          1.8
71            6.1          2.8           4.0          1.3
72            6.3          2.5           4.9          1.5
73            6.1          2.8           4.7          1.2
74            6.4          2.9           4.3          1.3
75            6.6          3.0           4.4          1.4
76            6.8          2.8           4.8          1.4
77            6.7          3.0           5.0          1.7
78            6.0          2.9           4.5          1.5
79            5.7          2.6           3.5          1.0
80            5.5          2.4           3.8          1.1
81            5.5          2.4           3.7          1.0
82            5.8          2.7           3.9          1.2
83            6.0          2.7           5.1          1.6
84            5.4          3.0           4.5          1.5
85            6.0          3.4           4.5          1.6
86            6.7          3.1           4.7          1.5
87            6.3          2.3           4.4          1.3
88            5.6          3.0           4.1          1.3
89            5.5          2.5           4.0          1.3
90            5.5          2.6           4.4          1.2
91            6.1          3.0           4.6          1.4
92            5.8          2.6           4.0          1.2
93            5.0          2.3           3.3          1.0
94            5.6          2.7           4.2          1.3
95            5.7          3.0           4.2          1.2
96            5.7          2.9           4.2          1.3
97            6.2          2.9           4.3          1.3
98            5.1          2.5           3.0          1.1
99            5.7          2.8           4.1          1.3
100           6.3          3.3           6.0          2.5
101           5.8          2.7           5.1          1.9
102           7.1          3.0           5.9          2.1
103           6.3          2.9           5.6          1.8
104           6.5          3.0           5.8          2.2
105           7.6          3.0           6.6          2.1
106           4.9          2.5           4.5          1.7
107           7.3          2.9           6.3          1.8
108           6.7          2.5           5.8          1.8
109           7.2          3.6           6.1          2.5
110           6.5          3.2           5.1          2.0
111           6.4          2.7           5.3          1.9
112           6.8          3.0           5.5          2.1
113           5.7          2.5           5.0          2.0
114           5.8          2.8           5.1          2.4
115           6.4          3.2           5.3          2.3
116           6.5          3.0           5.5          1.8
117           7.7          3.8           6.7          2.2
118           7.7          2.6           6.9          2.3
119           6.0          2.2           5.0          1.5
120           6.9          3.2           5.7          2.3
121           5.6          2.8           4.9          2.0
122           7.7          2.8           6.7          2.0
123           6.3          2.7           4.9          1.8
124           6.7          3.3           5.7          2.1
125           7.2          3.2           6.0          1.8
126           6.2          2.8           4.8          1.8
127           6.1          3.0           4.9          1.8
128           6.4          2.8           5.6          2.1
129           7.2          3.0           5.8          1.6
130           7.4          2.8           6.1          1.9
131           7.9          3.8           6.4          2.0
132           6.4          2.8           5.6          2.2
133           6.3          2.8           5.1          1.5
134           6.1          2.6           5.6          1.4
135           7.7          3.0           6.1          2.3
136           6.3          3.4           5.6          2.4
137           6.4          3.1           5.5          1.8
138           6.0          3.0           4.8          1.8
139           6.9          3.1           5.4          2.1
140           6.7          3.1           5.6          2.4
141           6.9          3.1           5.1          2.3
142           5.8          2.7           5.1          1.9
143           6.8          3.2           5.9          2.3
144           6.7          3.3           5.7          2.5
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

In [ ]:
iris.columns = iris.columns.str.replace(' ', '_')
iris.head(3)

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2

In [ ]:
# 데이터타입 확인하기
iris.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
dtype: object

In [ ]:
# 데이터 타입 변경하기
iris['sepal_length'] = iris['sepal_width'].astype('int')
iris[['sepal_width', 'petal_length']] = \
iris[['sepal_width', 'petal_length']].astype('int')
iris.head(3)

   sepal_length  sepal_width  petal_length  petal_width
0             3            3             1          0.2
1             3            3             1          0.2
2             3            3             1          0.2

In [ ]:
# row 선택하기
# 1. 붓꽃 데이터 불러오기
from sklearn.datasets import load_iris
iris = load_iris()
# 2. 데이터프레임으로 변환
iris = pd.DataFrame(iris.data, columns = iris.feature_names)
# 3. row선택
iris[1:4]

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2

In [ ]:
# 컬럼 선택하기
iris['sepal length (cm)'].head(4)

0    5.1
1    4.9
2    4.7
3    4.6
Name: sepal length (cm), dtype: float64

In [ ]:
# 컬럼 2개이상 선택하기
iris[['sepal length (cm)', 'sepal width (cm)']].head(4)

   sepal length (cm)  sepal width (cm)
0                5.1               3.5
1                4.9               3.0
2                4.7               3.2
3                4.6               3.1

In [ ]:
# 행과 열 선택하기
iris.iloc[1:4]

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2

In [ ]:
iris.iloc[[1, 3, 5], 2:4]

   petal length (cm)  petal width (cm)
1                1.4               0.2
3                1.5               0.2
5                1.7               0.4

In [ ]:
iris.iloc[:, [True, True, False, True]]

     sepal length (cm)  sepal width (cm)  petal width (cm)
0                  5.1               3.5               0.2
1                  4.9               3.0               0.2
2                  4.7               3.2               0.2
3                  4.6               3.1               0.2
4                  5.0               3.6               0.2
5                  5.4               3.9               0.4
6                  4.6               3.4               0.3
7                  5.0               3.4               0.2
8                  4.4               2.9               0.2
9                  4.9               3.1               0.1
10                 5.4               3.7               0.2
11                 4.8               3.4               0.2
12                 4.8               3.0               0.1
13                 4.3               3.0               0.1
14                 5.8               4.0               0.2
15                 5.7               4.4               0.4
16                 5.4               3.9               0.4
17                 5.1               3.5               0.3
18                 5.7               3.8               0.3
19                 5.1               3.8               0.3
20                 5.4               3.4               0.2
21                 5.1               3.7               0.4
22                 4.6               3.6               0.2
23                 5.1               3.3               0.5
24                 4.8               3.4               0.2
25                 5.0               3.0               0.2
26                 5.0               3.4               0.4
27                 5.2               3.5               0.2
28                 5.2               3.4               0.2
29                 4.7               3.2               0.2
30                 4.8               3.1               0.2
31                 5.4               3.4               0.4
32                 5.2               4.1               0.1
33                 5.5               4.2               0.2
34                 4.9               3.1               0.2
35                 5.0               3.2               0.2
36                 5.5               3.5               0.2
37                 4.9               3.6               0.1
38                 4.4               3.0               0.2
39                 5.1               3.4               0.2
40                 5.0               3.5               0.3
41                 4.5               2.3               0.3
42                 4.4               3.2               0.2
43                 5.0               3.5               0.6
44                 5.1               3.8               0.4
45                 4.8               3.0               0.3
46                 5.1               3.8               0.2
47                 4.6               3.2               0.2
48                 5.3               3.7               0.2
49                 5.0               3.3               0.2
50                 7.0               3.2               1.4
51                 6.4               3.2               1.5
52                 6.9               3.1               1.5
53                 5.5               2.3               1.3
54                 6.5               2.8               1.5
55                 5.7               2.8               1.3
56                 6.3               3.3               1.6
57                 4.9               2.4               1.0
58                 6.6               2.9               1.3
59                 5.2               2.7               1.4
60                 5.0               2.0               1.0
61                 5.9               3.0               1.5
62                 6.0               2.2               1.0
63                 6.1               2.9               1.4
64                 5.6               2.9               1.3
65                 6.7               3.1               1.4
66                 5.6               3.0               1.5
67                 5.8               2.7               1.0
68                 6.2               2.2               1.5
69                 5.6               2.5               1.1
70                 5.9               3.2               1.8
71                 6.1               2.8               1.3
72                 6.3               2.5               1.5
73                 6.1               2.8               1.2
74                 6.4               2.9               1.3
75                 6.6               3.0               1.4
76                 6.8               2.8               1.4
77                 6.7               3.0               1.7
78                 6.0               2.9               1.5
79                 5.7               2.6               1.0
80                 5.5               2.4               1.1
81                 5.5               2.4               1.0
82                 5.8               2.7               1.2
83                 6.0               2.7               1.6
84                 5.4               3.0               1.5
85                 6.0               3.4               1.6
86                 6.7               3.1               1.5
87                 6.3               2.3               1.3
88                 5.6               3.0               1.3
89                 5.5               2.5               1.3
90                 5.5               2.6               1.2
91                 6.1               3.0               1.4
92                 5.8               2.6               1.2
93                 5.0               2.3               1.0
94                 5.6               2.7               1.3
95                 5.7               3.0               1.2
96                 5.7               2.9               1.3
97                 6.2               2.9               1.3
98                 5.1               2.5               1.1
99                 5.7               2.8               1.3
100                6.3               3.3               2.5
101                5.8               2.7               1.9
102                7.1               3.0               2.1
103                6.3               2.9               1.8
104                6.5               3.0               2.2
105                7.6               3.0               2.1
106                4.9               2.5               1.7
107                7.3               2.9               1.8
108                6.7               2.5               1.8
109                7.2               3.6               2.5
110                6.5               3.2               2.0
111                6.4               2.7               1.9
112                6.8               3.0               2.1
113                5.7               2.5               2.0
114                5.8               2.8               2.4
115                6.4               3.2               2.3
116                6.5               3.0               1.8
117                7.7               3.8               2.2
118                7.7               2.6               2.3
119                6.0               2.2               1.5
120                6.9               3.2               2.3
121                5.6               2.8               2.0
122                7.7               2.8               2.0
123                6.3               2.7               1.8
124                6.7               3.3               2.1
125                7.2               3.2               1.8
126                6.2               2.8               1.8
127                6.1               3.0               1.8
128                6.4               2.8               2.1
129                7.2               3.0               1.6
130                7.4               2.8               1.9
131                7.9               3.8               2.0
132                6.4               2.8               2.2
133                6.3               2.8               1.5
134                6.1               2.6               1.4
135                7.7               3.0               2.3
136                6.3               3.4               2.4
137                6.4               3.1               1.8
138                6.0               3.0               1.8
139                6.9               3.1               2.1
140                6.7               3.1               2.4
141                6.9               3.1               2.3
142                5.8               2.7               1.9
143                6.8               3.2               2.3
144                6.7               3.3               2.5
145                6.7               3.0               2.3
146                6.3               2.5               1.9
147                6.5               3.0               2.0
148                6.2               3.4               2.3
149                5.9               3.0               1.8

In [ ]:
iris.loc[1:3]

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2

In [ ]:
iris.loc[[1, 2], 'sepal length (cm)':'petal length (cm)']

   sepal length (cm)  sepal width (cm)  petal length (cm)
1                4.9               3.0                1.4
2                4.7               3.2                1.3

In [ ]:
# 선택한 값 변경
# 1. 성적 데이터 생성
score = pd.DataFrame({'국어':[100, 80], '수학':[75, 90], 
                     '영어':[90, 95]}, index = ['장화', '홍련'])
score.loc['홍련', '영어'] = 100
score['국어'] = score['국어'] - 5
score

    국어  수학   영어
장화  95  75   90
홍련  75  90  100

In [ ]:
# row/column 추가
new_students = pd.DataFrame({'국어':[70, 85], '수학':[65, 100], 
                            '영어':[95, 65]}, index = ['콩쥐', '팥쥐'])
score = score.append(new_students)
score

C:\Users\LG\AppData\Local\Temp\ipykernel_13176\2485326606.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  score = score.append(new_students)

    국어   수학   영어
장화  95   75   90
홍련  75   90  100
콩쥐  70   65   95
팥쥐  85  100   65

In [ ]:
new_students1 = pd.Series({'국어':85, '수학':55, '영어':95}, name = '해님')
score = score.append(new_students1)

C:\Users\LG\AppData\Local\Temp\ipykernel_13176\4046466391.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  score = score.append(new_students1)

In [ ]:
new_students2 = {'국어':75, '수학':80, '영어':80}
score.append(new_students2, ignore_index = True)

C:\Users\LG\AppData\Local\Temp\ipykernel_13176\2626775036.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  score.append(new_students2, ignore_index = True)

   국어   수학   영어
0  95   75   90
1  75   90  100
2  70   65   95
3  85  100   65
4  85   55   95
5  75   80   80

In [ ]:
# column값 추가
science = [80, 70, 90, 85, 75]
score['과학'] = science
score['학년'] = 1
score

    국어   수학   영어  과학  학년
장화  95   75   90  80   1
홍련  75   90  100  70   1
콩쥐  70   65   95  90   1
팥쥐  85  100   65  85   1
해님  85   55   95  75   1

In [ ]:
score['과학'] = score['과학'] + 5
score['총점'] = score['국어'] + score['수학'] + score['영어'] + score['과학']
score

    국어   수학   영어  과학  학년   총점
장화  95   75   90  85   1  345
홍련  75   90  100  75   1  340
콩쥐  70   65   95  95   1  325
팥쥐  85  100   65  90   1  340
해님  85   55   95  80   1  315

In [ ]:
score.drop('장화', inplace = True)
score.drop(columns = ['과학', '학년', '총점'], inplace = True)
score

    국어   수학   영어
홍련  75   90  100
콩쥐  70   65   95
팥쥐  85  100   65
해님  85   55   95

In [ ]:
students = pd.DataFrame({'이름' : ['장화', '홍련', '콩쥐', '팥쥐', '해님', '달님'], 
                        '국어' : [70, 85, None, 100, None, 85],
                        '수학' : [65, 100, 80, 95, None, 70]})
students[students['이름'] == '장화']

   이름    국어    수학
0  장화  70.0  65.0

In [ ]:
students[(students['국어'] >= 80) & (students['수학'] >= 80)]

   이름     국어     수학
1  홍련   85.0  100.0
3  팥쥐  100.0   95.0

In [ ]:
students

   이름     국어     수학
0  장화   70.0   65.0
1  홍련   85.0  100.0
2  콩쥐    NaN   80.0
3  팥쥐  100.0   95.0
4  해님    NaN    NaN
5  달님   85.0   70.0

In [ ]:
students.loc[6, '이름' : '수학'] = ['별님', 50, 60]
students.loc[(students['국어'] >= 80) & (students['수학'] >= 70), '합격'] = 'Pass'
students.loc[students['합격'] != 'Pass', '합격'] = 'Fail'
students

   이름     국어     수학    합격
0  장화   70.0   65.0  Fail
1  홍련   85.0  100.0  Pass
2  콩쥐    NaN   80.0  Fail
3  팥쥐  100.0   95.0  Pass
4  해님    NaN    NaN  Fail
5  달님   85.0   70.0  Pass
6  별님   50.0   60.0  Fail

In [ ]:
condition_list = [(students['국어'] >= 90),
                 (students['국어'] >= 80) & (students['국어'] < 90),
                 (students['국어'] >= 70) & (students['국어'] < 80)]
choice_list = ['A', 'B', 'C']
students['점수'] = np.select(condition_list, choice_list, default = 'F')
students

   이름     국어     수학    합격 점수
0  장화   70.0   65.0  Fail  C
1  홍련   85.0  100.0  Pass  B
2  콩쥐    NaN   80.0  Fail  F
3  팥쥐  100.0   95.0  Pass  A
4  해님    NaN    NaN  Fail  F
5  달님   85.0   70.0  Pass  B
6  별님   50.0   60.0  Fail  F

In [ ]:
# 결측값 탐색 : isna()
students.isna()

      이름     국어     수학     합격     점수
0  False  False  False  False  False
1  False  False  False  False  False
2  False   True  False  False  False
3  False  False  False  False  False
4  False   True   True  False  False
5  False  False  False  False  False
6  False  False  False  False  False

In [ ]:
# 결측값 탐색 : notna()
students.notna()

     이름     국어     수학    합격    점수
0  True   True   True  True  True
1  True   True   True  True  True
2  True  False   True  True  True
3  True   True   True  True  True
4  True  False  False  True  True
5  True   True   True  True  True
6  True   True   True  True  True

In [ ]:
# 열 합계
students.isna().sum()

이름    0
국어    2
수학    1
합격    0
점수    0
dtype: int64

In [ ]:
# 행 합계
students.isna().sum(1)

0    0
1    0
2    1
3    0
4    2
5    0
6    0
dtype: int64

In [ ]:
students.dropna()

   이름     국어     수학    합격 점수
0  장화   70.0   65.0  Fail  C
1  홍련   85.0  100.0  Pass  B
3  팥쥐  100.0   95.0  Pass  A
5  달님   85.0   70.0  Pass  B
6  별님   50.0   60.0  Fail  F

In [ ]:
students.dropna(thresh=4)

   이름     국어     수학    합격 점수
0  장화   70.0   65.0  Fail  C
1  홍련   85.0  100.0  Pass  B
2  콩쥐    NaN   80.0  Fail  F
3  팥쥐  100.0   95.0  Pass  A
5  달님   85.0   70.0  Pass  B
6  별님   50.0   60.0  Fail  F

In [ ]:
# 0으로 결측치 채우기
health = pd.DataFrame({'연도':[2017,2018,2019,2020,2021,2022],
                     '키':[160,162,165,None,None,166],
                     '몸무게':[53,52,None,50,51,54],
                     '시력':[1.2,None,1.2,1.2,1.1,0.8],
                     '병결':[None, None, None, 2, None, 1]})
health.fillna(0)

     연도      키   몸무게   시력   병결
0  2017  160.0  53.0  1.2  0.0
1  2018  162.0  52.0  0.0  0.0
2  2019  165.0   0.0  1.2  0.0
3  2020    0.0  50.0  1.2  2.0
4  2021    0.0  51.0  1.1  0.0
5  2022  166.0  54.0  0.8  1.0

In [ ]:
# 평균으로 결측치 채우기
health.fillna(health.mean())

     연도       키   몸무게   시력   병결
0  2017  160.00  53.0  1.2  1.5
1  2018  162.00  52.0  1.1  1.5
2  2019  165.00  52.0  1.2  1.5
3  2020  163.25  50.0  1.2  2.0
4  2021  163.25  51.0  1.1  1.5
5  2022  166.00  54.0  0.8  1.0

In [ ]:
# 병결 결측치는 0으로, 몸무게 결측치는 평균으로 대체하기
health['병결'] = health['병결'].fillna(0)
health['몸무게'] = health['몸무게'].fillna(health['몸무게'].mean())
health

     연도      키   몸무게   시력   병결
0  2017  160.0  53.0  1.2  0.0
1  2018  162.0  52.0  NaN  0.0
2  2019  165.0  52.0  1.2  0.0
3  2020    NaN  50.0  1.2  2.0
4  2021    NaN  51.0  1.1  0.0
5  2022  166.0  54.0  0.8  1.0

In [ ]:
# 키와 시력은 켤측값이 등정하기 바로 전값으로 대체하기
health.fillna(method = 'pad', inplace = True)
health

     연도      키   몸무게   시력   병결
0  2017  160.0  53.0  1.2  0.0
1  2018  162.0  52.0  1.2  0.0
2  2019  165.0  52.0  1.2  0.0
3  2020  165.0  50.0  1.2  2.0
4  2021  165.0  51.0  1.1  0.0
5  2022  166.0  54.0  0.8  1.0

In [ ]:
# 중복행 제거하기
health['키'].drop_duplicates()

0    160.0
1    162.0
2    165.0
5    166.0
Name: 키, dtype: float64

In [ ]:
set(health['키'])

{160.0, 162.0, 165.0, 166.0}

In [ ]:
health[['시력', '병결']].drop_duplicates()

    시력   병결
0  1.2  0.0
3  1.2  2.0
4  1.1  0.0
5  0.8  1.0

In [ ]:
from sklearn.datasets import load_iris
iris = load_iris()
iris = pd.DataFrame(iris.data, columns = iris.feature_names)
iris.sort_index(ascending = False, inplace = True)
iris.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
149                5.9               3.0                5.1               1.8
148                6.2               3.4                5.4               2.3
147                6.5               3.0                5.2               2.0
146                6.3               2.5                5.0               1.9
145                6.7               3.0                5.2               2.3

In [ ]:
iris.sort_index(axis = 1, inplace = True)
iris.head()

     petal length (cm)  petal width (cm)  sepal length (cm)  sepal width (cm)
149                5.1               1.8                5.9               3.0
148                5.4               2.3                6.2               3.4
147                5.2               2.0                6.5               3.0
146                5.0               1.9                6.3               2.5
145                5.2               2.3                6.7               3.0

In [ ]:
iris.sort_values( 'petal length (cm)')
iris.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
iris.sort_values(['petal length (cm)', 'sepal length (cm)'])

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                 4.6               3.6                1.0               0.2
13                 4.3               3.0                1.1               0.1
35                 5.0               3.2                1.2               0.2
14                 5.8               4.0                1.2               0.2
38                 4.4               3.0                1.3               0.2
42                 4.4               3.2                1.3               0.2
41                 4.5               2.3                1.3               0.3
2                  4.7               3.2                1.3               0.2
40                 5.0               3.5                1.3               0.3
16                 5.4               3.9                1.3               0.4
36                 5.5               3.5                1.3               0.2
8                  4.4               2.9                1.4               0.2
6                  4.6               3.4                1.4               0.3
47                 4.6               3.2                1.4               0.2
12                 4.8               3.0                1.4               0.1
45                 4.8               3.0                1.4               0.3
1                  4.9               3.0                1.4               0.2
37                 4.9               3.6                1.4               0.1
4                  5.0               3.6                1.4               0.2
49                 5.0               3.3                1.4               0.2
0                  5.1               3.5                1.4               0.2
17                 5.1               3.5                1.4               0.3
28                 5.2               3.4                1.4               0.2
33                 5.5               4.2                1.4               0.2
3                  4.6               3.1                1.5               0.2
9                  4.9               3.1                1.5               0.1
34                 4.9               3.1                1.5               0.2
7                  5.0               3.4                1.5               0.2
19                 5.1               3.8                1.5               0.3
21                 5.1               3.7                1.5               0.4
39                 5.1               3.4                1.5               0.2
27                 5.2               3.5                1.5               0.2
32                 5.2               4.1                1.5               0.1
48                 5.3               3.7                1.5               0.2
10                 5.4               3.7                1.5               0.2
31                 5.4               3.4                1.5               0.4
15                 5.7               4.4                1.5               0.4
29                 4.7               3.2                1.6               0.2
11                 4.8               3.4                1.6               0.2
30                 4.8               3.1                1.6               0.2
25                 5.0               3.0                1.6               0.2
26                 5.0               3.4                1.6               0.4
43                 5.0               3.5                1.6               0.6
46                 5.1               3.8                1.6               0.2
23                 5.1               3.3                1.7               0.5
5                  5.4               3.9                1.7               0.4
20                 5.4               3.4                1.7               0.2
18                 5.7               3.8                1.7               0.3
24                 4.8               3.4                1.9               0.2
44                 5.1               3.8                1.9               0.4
98                 5.1               2.5                3.0               1.1
57                 4.9               2.4                3.3               1.0
93                 5.0               2.3                3.3               1.0
60                 5.0               2.0                3.5               1.0
79                 5.7               2.6                3.5               1.0
64                 5.6               2.9                3.6               1.3
81                 5.5               2.4                3.7               1.0
80                 5.5               2.4                3.8               1.1
59                 5.2               2.7                3.9               1.4
69                 5.6               2.5                3.9               1.1
82                 5.8               2.7                3.9               1.2
53                 5.5               2.3                4.0               1.3
89                 5.5               2.5                4.0               1.3
92                 5.8               2.6                4.0               1.2
62                 6.0               2.2                4.0               1.0
71                 6.1               2.8                4.0               1.3
88                 5.6               3.0                4.1               1.3
99                 5.7               2.8                4.1               1.3
67                 5.8               2.7                4.1               1.0
94                 5.6               2.7                4.2               1.3
95                 5.7               3.0                4.2               1.2
96                 5.7               2.9                4.2               1.3
61                 5.9               3.0                4.2               1.5
97                 6.2               2.9                4.3               1.3
74                 6.4               2.9                4.3               1.3
90                 5.5               2.6                4.4               1.2
87                 6.3               2.3                4.4               1.3
75                 6.6               3.0                4.4               1.4
65                 6.7               3.1                4.4               1.4
106                4.9               2.5                4.5               1.7
84                 5.4               3.0                4.5               1.5
66                 5.6               3.0                4.5               1.5
55                 5.7               2.8                4.5               1.3
78                 6.0               2.9                4.5               1.5
85                 6.0               3.4                4.5               1.6
68                 6.2               2.2                4.5               1.5
51                 6.4               3.2                4.5               1.5
91                 6.1               3.0                4.6               1.4
54                 6.5               2.8                4.6               1.5
58                 6.6               2.9                4.6               1.3
63                 6.1               2.9                4.7               1.4
73                 6.1               2.8                4.7               1.2
56                 6.3               3.3                4.7               1.6
86                 6.7               3.1                4.7               1.5
50                 7.0               3.2                4.7               1.4
70                 5.9               3.2                4.8               1.8
138                6.0               3.0                4.8               1.8
126                6.2               2.8                4.8               1.8
76                 6.8               2.8                4.8               1.4
121                5.6               2.8                4.9               2.0
127                6.1               3.0                4.9               1.8
72                 6.3               2.5                4.9               1.5
123                6.3               2.7                4.9               1.8
52                 6.9               3.1                4.9               1.5
113                5.7               2.5                5.0               2.0
119                6.0               2.2                5.0               1.5
146                6.3               2.5                5.0               1.9
77                 6.7               3.0                5.0               1.7
101                5.8               2.7                5.1               1.9
114                5.8               2.8                5.1               2.4
142                5.8               2.7                5.1               1.9
149                5.9               3.0                5.1               1.8
83                 6.0               2.7                5.1               1.6
133                6.3               2.8                5.1               1.5
110                6.5               3.2                5.1               2.0
141                6.9               3.1                5.1               2.3
147                6.5               3.0                5.2               2.0
145                6.7               3.0                5.2               2.3
111                6.4               2.7                5.3               1.9
115                6.4               3.2                5.3               2.3
148                6.2               3.4                5.4               2.3
139                6.9               3.1                5.4               2.1
137                6.4               3.1                5.5               1.8
116                6.5               3.0                5.5               1.8
112                6.8               3.0                5.5               2.1
134                6.1               2.6                5.6               1.4
103                6.3               2.9                5.6               1.8
136                6.3               3.4                5.6               2.4
128                6.4               2.8                5.6               2.1
132                6.4               2.8                5.6               2.2
140                6.7               3.1                5.6               2.4
124                6.7               3.3                5.7               2.1
144                6.7               3.3                5.7               2.5
120                6.9               3.2                5.7               2.3
104                6.5               3.0                5.8               2.2
108                6.7               2.5                5.8               1.8
129                7.2               3.0                5.8               1.6
143                6.8               3.2                5.9               2.3
102                7.1               3.0                5.9               2.1
100                6.3               3.3                6.0               2.5
125                7.2               3.2                6.0               1.8
109                7.2               3.6                6.1               2.5
130                7.4               2.8                6.1               1.9
135                7.7               3.0                6.1               2.3
107                7.3               2.9                6.3               1.8
131                7.9               3.8                6.4               2.0
105                7.6               3.0                6.6               2.1
117                7.7               3.8                6.7               2.2
122                7.7               2.8                6.7               2.0
118                7.7               2.6                6.9               2.3

In [ ]:
# 단순연결-열방향 결합
HR1 = pd.DataFrame({'이름' : ['장화', '홍련'],
                   '부서':['영업', '회계'],
                   '직급':['팀장', '사원']})
HR2 = pd.DataFrame({'이름' : ['콩쥐', '팥쥐'],
                   '직급' : ['사원', '팀장'],
                   '부서' : ['영업', '인사']})

HR3 = pd.DataFrame({'이름' : ['콩쥐', '팥쥐'],
                  '부서' : ['영업', '인사'],
                  '급여' : [3500, 2800]})

HR4 = pd.Series({1:2500}, name = '급여')

HR5 = pd.DataFrame({'급여' : [4500, 3000, 3500]})

In [ ]:
HR1

   이름  부서  직급
0  장화  영업  팀장
1  홍련  회계  사원

In [ ]:
HR2

   이름  직급  부서
0  콩쥐  사원  영업
1  팥쥐  팀장  인사

In [ ]:
HR3

   이름  부서    급여
0  콩쥐  영업  3500
1  팥쥐  인사  2800

In [ ]:
HR4

1    2500
Name: 급여, dtype: int64

In [ ]:
HR5

     급여
0  4500
1  3000
2  3500

In [ ]:
pd.concat([HR1, HR2], ignore_index = True)

   이름  부서  직급
0  장화  영업  팀장
1  홍련  회계  사원
2  콩쥐  영업  사원
3  팥쥐  인사  팀장

In [ ]:
pd.concat([HR1, HR3], ignore_index = True)

   이름  부서   직급      급여
0  장화  영업   팀장     NaN
1  홍련  회계   사원     NaN
2  콩쥐  영업  NaN  3500.0
3  팥쥐  인사  NaN  2800.0

In [ ]:
pd.concat([HR1, HR4], axis = 1)

   이름  부서  직급      급여
0  장화  영업  팀장     NaN
1  홍련  회계  사원  2500.0

In [ ]:
pd.concat([HR1, HR5], axis = 1)

    이름   부서   직급    급여
0   장화   영업   팀장  4500
1   홍련   회계   사원  3000
2  NaN  NaN  NaN  3500

In [ ]:
# 조인
product = pd.DataFrame({'상품코드' : ['G1', 'G2', 'G3', 'G4'],
                       '상품명' : ['우유', '감자', '빵', '치킨']})
sale = pd.DataFrame({'주문번호' : [1001, 1002, 1002, 1003, 1004],
                    '상품코드' : ['G4', 'G3', 'G1', 'G3', 'G5'],
                    '주문수량' : [1, 4, 2, 2, 3]})
sale.merge(product, on = '상품코드', how = 'inner')

   주문번호 상품코드  주문수량 상품명
0  1001   G4     1  치킨
1  1002   G3     4   빵
2  1003   G3     2   빵
3  1002   G1     2  우유

In [ ]:
sale

   주문번호 상품코드  주문수량
0  1001   G4     1
1  1002   G3     4
2  1002   G1     2
3  1003   G3     2
4  1004   G5     3

In [ ]:
product

  상품코드 상품명
0   G1  우유
1   G2  감자
2   G3   빵
3   G4  치킨

In [ ]:
sale.merge(product, on='상품코드', how='outer', sort=True)

     주문번호 상품코드  주문수량  상품명
0  1002.0   G1   2.0   우유
1     NaN   G2   NaN   감자
2  1002.0   G3   4.0    빵
3  1003.0   G3   2.0    빵
4  1001.0   G4   1.0   치킨
5  1004.0   G5   3.0  NaN

In [ ]:
sale.merge(product, left_on = '상품코드', right_on = '상품코드', how = 'left')

   주문번호 상품코드  주문수량  상품명
0  1001   G4     1   치킨
1  1002   G3     4    빵
2  1002   G1     2   우유
3  1003   G3     2    빵
4  1004   G5     3  NaN

### 데이터 요약

In [ ]:
# 환경셋팅
import pandas as pd
from sklearn.datasets import load_iris

In [ ]:
# 데이터 정의
IRIS = load_iris()
iris = pd.DataFrame(data = IRIS.data, columns = IRIS.feature_names)

In [ ]:
iris['class'] = IRIS.target
iris['class'] = iris['class'].map({0:'setosa', 1:'versicolor', 2:'virginica'})
# 그룹화와 집계(평균)
iris.groupby(by = 'class').mean()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
class,,,,
setosa,5.006,3.428,1.462,0.246
versicolor,5.936,2.770,4.260,1.326
virginica,6.588,2.974,5.552,2.026

In [ ]:
# 그룹화와 집계(중앙값)
iris.groupby(by = 'class').median()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
class,,,,
setosa,5.0,3.4,1.50,0.2
versicolor,5.9,2.8,4.35,1.3
virginica,6.5,3.0,5.55,2.0

### 도수분포표
 - pd.Series(DataFrame['컬럼명'].value_counts(

In [ ]:
pd.Series(iris['class']).value_counts()

setosa        50
versicolor    50
virginica     50
Name: class, dtype: int64

In [ ]:
# 구간 나눠서 도수분포표 작성하기
# 1. 구간 나누기
iris['petal width level'] = pd.qcut(iris['petal width (cm)'], q = 3, labels = ['short', 'middle', 'long'])
# 2. 도수분포표 작성
pd.Series(iris['petal width level']).value_counts().to_frame()  #  to_frame() : 결과를 데이터프레임으로 변경

        petal width level
middle                 52
short                  50
long                   48

In [ ]:
# 두 개의 데이터 기준 : crosstab() 함수 이용
pd.crosstab(iris['petal width level'], iris['class'])

class              setosa  versicolor  virginica
petal width level
short                  50           0          0
middle                  0          48          4
long                    0           2         46

### 데이터 재구조화

In [ ]:
# 라이브러리 임포트
import pandas as pd

score = {'학년':[1, 1, 1, 1, 2, 2],
         '반':['A', 'A', 'B', 'B', 'C', 'C'],
         '성별':['여자', '남자', '여자', '남자', '여자', '남자'],
         '성적':[76, 88, 85, 72, 68, 70]}

# 데이터프레임화
score = pd.DataFrame(score)
score

   학년  반  성별  성적
0   1  A  여자  76
1   1  A  남자  88
2   1  B  여자  85
3   1  B  남자  72
4   2  C  여자  68
5   2  C  남자  70

In [ ]:
# 피벗 테이블 생성하기
score = score.pivot_table(index = ['학년', '반'], columns = '성별', values = '성적')
score

성별    남자  여자
학년 반
1  A  88  76
   B  72  85
2  C  70  68

In [ ]:
# 멜트(melt)
score.reset_index().melt(id_vars = ['학년', '반'], var_name = '성별', value_name = '성적')

   학년  반  성별  성적
0   1  A  남자  88
1   1  B  남자  72
2   2  C  남자  70
3   1  A  여자  76
4   1  B  여자  85
5   2  C  여자  68

### 데이터프레임에 함수 적용하기
 - Apply, Map함수

In [ ]:
# 1. Apply함수
# 라이브러리 임포트
import numpy as np
# apply함수 적용
score.apply(np.sqrt, axis = 0)

성별          남자        여자
학년 반
1  A  9.380832  8.717798
   B  8.485281  9.219544
2  C  8.366600  8.246211

In [ ]:
score.apply(np.max, axis = 0)

성별
남자    88
여자    85
dtype: int64

In [ ]:
# 직접 정의한 함수에 apply함수 적용
def plus_five(val) : 
  return val + 5
score.apply(plus_five)

성별    남자  여자
학년 반
1  A  93  81
   B  77  90
2  C  75  73

In [ ]:
def class_avg(df) : 
  return np.ceil((df['남자'] + df['여자'])/2)
score.apply(class_avg, axis = 1)

학년  반
1   A    82.0
    B    79.0
2   C    69.0
dtype: float64

In [ ]:
# 2. Map함수
score['남자'].map(lambda x : x+5)

학년  반
1   A    93
    B    77
2   C    75
Name: 남자, dtype: int64

### 문자열 데이터 변환하기

In [ ]:
# 특정 위치 글자 추출하기
# Series.str() : 데이터프레임의 문자열을 추출하는 데 사용됨
# 라이브러리 임포트 
import pandas as pd
# 데이터 정의
landmark = pd.DataFrame({'name':['광화문,','호미곶','첨성대'],
                         'location':['서울 종로구 사직로 161',
                                     '경북 포항시 남구 호미곶면 대보리 150',
                                     '경북 경주시 인왕동 839-1']})
# 글자 추출
landmark['location'].str[3:6]

0    종로구
1    포항시
2    경주시
Name: location, dtype: object

In [ ]:
# 문자열 분할
landmark['location'].str.split(" ", expand = True)

    0    1    2      3     4     5
0  서울  종로구  사직로    161  None  None
1  경북  포항시   남구   호미곶면   대보리   150
2  경북  경주시  인왕동  839-1  None  None

In [ ]:
# 특정한 순서의 값만 선택할 때 
landmark['loc_1'] = landmark['location'].str.split(" ").str[0]
# landmark

   name                location loc_1
0  광화문,          서울 종로구 사직로 161    서울
1   호미곶  경북 포항시 남구 호미곶면 대보리 150    경북
2   첨성대        경북 경주시 인왕동 839-1    경북

In [ ]:
# 탐색
# 시작 글자
landmark['location'].str.startswith('서울')

# 끝 글자
landmark['location'].str.endswith('1')

# 포함하는 글자
landmark['location'].str.contains('1')

0    True
1    True
2    True
Name: location, dtype: bool

### 날짜 데이터

In [ ]:
# 현재 날짜 데이터 추출하기
from datetime import datetime
datetime.today()

datetime.datetime(2022, 12, 19, 8, 18, 55, 294111)

In [ ]:
# 연도만 추출하기
datetime.today().year

2022

In [ ]:
# 문자열 데이터를 날짜로 바꾸기 : strptime
datetime.strptime('2022-12-19 17:33:00', '%Y-%m-%d %H:%M:%S')

datetime.datetime(2022, 12, 19, 17, 33)

In [ ]:
# 날짜 형식을 문자열로 변환 : strftime
time = datetime.today()
time.strftime('%Y-%m-%d %H:%M:%S')

'2022-12-19 08:35:54'

In [ ]:
# 날짜 데이터의 연산 : timedelta 함수
from datetime import timedelta, datetime
time = datetime.today()
time + timedelta(days = 100)

datetime.datetime(2023, 3, 29, 11, 11, 54, 901378)

In [ ]:
# cd /content/drive/MyDrive/Colab Notebooks/adp실기

/content/drive/MyDrive/Colab Notebooks/adp실기

In [ ]:
# !git clone https://chw8207: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@github.com/chw8207/ADP-study.git

fatal: destination path 'ADP-study' already exists and is not an empty directory.

In [ ]:
# cd ADP-study/

/content/drive/MyDrive/Colab Notebooks/adp실기/ADP-study

In [ ]:
# 접근권한
!git config --global user.email 'chw8207@naver.com'
!git config --global user.name 'chw8207'

In [21]:
# 파일 커밋하기
!git add 데이터 핸들링.ipynb
!git commit -m "Connect Google Colab and Drive"

fatal: pathspec '데이터' did not match any files
On branch master

Initial commit

Untracked files:
	"\341\204\203\341\205\246\341\204\213\341\205\265\341\204\220\341\205\245 \341\204\222\341\205\242\341\206\253\341\204\203\341\205\263\341\206\257\341\204\205\341\205\265\341\206\274.ipynb"

nothing added to commit but untracked files present

In [19]:
!git push -u origin main

error: src refspec main does not match any.
error: failed to push some refs to 'https://chw8207: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@github.com/chw8207/ADP-study.git'